language: php

php:
  - 7.1
  - 7.2

env:
  - DATABASE_URL="mysql://root@127.0.0.1:3306/tests?charset=utf8mb4"
  - DATABASE_URL="postgres://postgres@127.0.0.1:5432/tests"

install:
  - composer install --no-interaction

before_script:
  - bin/console doctrine:database:create
  - bin/console doctrine:schema:create
  - bin/console doctrine:schema:validate

script:
  - vendor/bin/phpcs --standard=PSR2 src/Controller src/Entity src/Repository tests/
  - bin/phpunit
